### ISSUE TITLE
Visual C++2013 build broken.

### ISSUE THREAD

**Issue by Hoikas** [H-uru/libhsplasma#160]
`hsArraySize` uses features not available in VC++2013. There also seem to be lots of errors around the union in the ENDSWAP functions. Visual C++2013 is required by Korman due to Blender 2.79b's dependency on the same. It is presently not feasible to upgrade Korman to Blender 2.80.

**Comment by Deledrius** [comment]
What sort of error around the union?  Is it related to 3f42c89c49e925301ec9ff3312102febe514465c or is it an older problem?

**Comment by zrax** [comment]
VC++2013 was intentionally dropped, since I was not aware that Blender still required it...  I'll see how much compatibility I can repair, though I may have to exclude some features (like the tools I refactored).

**Comment by Hoikas** [comment]
As long as PyHSPlasma can build, that'll be enough ^_^
