### ISSUE TITLE
-nan(ind) is converted to a number

### ISSUE THREAD

**Issue by Hazado** [H-uru/libhsplasma#207]
I was working on the Great Tree Pub, when I noticed that if libhsplasma touches the ATC Anim files, the hsQuats changed "-nan(ind)" into a number.
This cause the below issue.
![image](https://user-images.githubusercontent.com/416114/120075389-e7e17e00-c055-11eb-87b9-4b4d29747c45.png)

**Comment by Hoikas** [comment]
Fixed by #225?

**Comment by Hazado** [comment]
yes the issue should be fixed
