### ISSUE TITLE
Shared Mesh issue

### ISSUE THREAD

**Issue by Hazado** [H-uru/libhsplasma#230]
Shared mesh for clothing when modified with PRPShop will disappear if you get too close to the clothing in game.
I found when doing a binary compare of before and after that the initial section of the binary was very different.
Replacing the initial section with the original changes would fix the disappearing clothes.

I think that the maxbones and penbones are not being saved correctly, or the structure of the file is somehow important to MOULA in displaying the clothing correctly. 
This only affects the visibility of the clothing when you get close to them.

![image](https://user-images.githubusercontent.com/416114/140165918-afe88dd3-f48d-4204-8873-db1bfd712a9e.png)

**Comment by dpogue** [comment]
Shared mesh? More like "shredded mesh" in this case...

Looks like whatever's going wrong is in the bounds of the plGeometrySpan.

**Comment by dpogue** [comment]
@Hazado Are you round-tripping these through PRC? It looks like the PRC writer doesn't include the LocalBounds of the geometry span, which means it probably defaults to an empty bounding box when compiling the PRC into a new object.

**Comment by Hazado** [comment]
I opened the file in prpshop, made my changes and saved it.
Exported to PO, compared to PO I had exported before.
Thats what your seeing above.
