### ISSUE TITLE
Uru:CC PRP files change when beaing read and written back

### ISSUE THREAD

**Issue by diafero** [H-uru/libhsplasma#64]
For example, reading and writing back `Gira_District_giraCanyon.prp` with my check-script (`scripts/prp-checkfiles.py -cp`) complains (amongst others) about

```
Type [0015]plCoordinateInterface, object CapBase06 changed but stay same size
Type [0015]plCoordinateInterface, object Fumerols29 changed changed size (337 => 333)
Type [0015]plCoordinateInterface, object Fumerols29 changed but stay same size
Type [0015]plCoordinateInterface, object Fumerols27 changed changed size (337 => 333)
Type [0015]plCoordinateInterface, object Fumerols27 changed but stay same size
Type [00D5]plPointShadowMaster, object ShadowLight-LampPost_2 changed but stay same size
Type [00D5]plPointShadowMaster, object ShadowLight-LampPost_3 changed changed size (97 => 93)
Type [00D5]plPointShadowMaster, object ShadowLight-LampPost_3 changed but stay same size
Type [00D5]plPointShadowMaster, object ShadowLight-LampPost_0 changed changed size (97 => 93)
Type [00D6]plDirectShadowMaster, object ShadowLightCaveOpening_3 changed but stay same size
Type [00D6]plDirectShadowMaster, object ShadowLightSun changed changed size (86 => 82)
Type [00FF]plStereizer, object cSfxStereize-LavaR changed changed size (73 => 69)
Type [00FF]plStereizer, object cSfxStereize-LavaR changed but stay same size
```

I'm pretty sure this is a regression, TPOTS files used to read and write back fine (except for physics). I'm currently doing a bisect.

**Comment by Hoikas** [comment]
This looks like libHSPlasma's better bit vector compression... IIRC

**Comment by diafero** [comment]
The result of the bisect is rather surprising...

```
125954fb65a6652c5b7bdb83cb2625aa97e723c4 is the first bad commit
commit 125954fb65a6652c5b7bdb83cb2625aa97e723c4
Author: diafero <diafero@arcor.de>
Date:   Mon Mar 19 15:17:01 2012 +0100

    prp-checkfiles: do not stop comparing objects after the first difference

:040000 040000 a76f536bc3286c8dc3ecfae4e3e393e3a722a623 941d6797e5625c2b745b0ed90c1f69c4c030c4ba M      Python
```

WTF? That really shouldn't change things...
I'm still investigating, but don't have any more time today.

**Comment by diafero** [comment]
Okay, I think I'm just too stupid to read. Prior to that commit, my script only had a single complaint, and I simply missed that one. You are probably right with your bit vector compression. Of course, this means that checking whether anything got actually lost, is much harder.

**Comment by zrax** [comment]
It would probably be easier to do a semantic comparison with something like PRC than with the binary objects themselves.  There are cases (hsBitVector being the most common) where the data may not be stored identically even though they are semantically equivalent.

**Comment by diafero** [comment]
The problem with that is that it won't catch errors in the read code -
it may read the data as being the same, even though for the game, they
actually are not the same.
